# Generated by Django 4.0.4 on 2022-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_bets',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fund_balance',
            field=models.CharField(default='100', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='past_results',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Newbie', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='total_bets_won',
            field=models.IntegerField(default=0),
        ),
    ]
