# Generated by Django 4.0.4 on 2022-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_current_bets_user_fund_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fund_balance',
            field=models.CharField(default=100, max_length=300),
        ),
    ]
