# Generated by Django 4.0.4 on 2022-05-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0002_rename_bets_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_category', models.CharField(max_length=150)),
                ('team_one', models.CharField(max_length=150)),
                ('team_two', models.CharField(max_length=150)),
                ('winning_team', models.CharField(max_length=150)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.bet')),
            ],
        ),
    ]
