# Generated by Django 4.0.4 on 2022-06-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_bet_amount_bet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='won',
            new_name='completed',
        ),
    ]
